### ISSUE TITLE
Running on Apple Silicon 

### ISSUE THREAD

**Issue by ceinem** [spookiej/docker-machine-for-mac#10]
Hi, this looks like a great replacement for docker for Mac. Have you maybe tried to run this on an ARM Mac? 
I tried setting it up on an M2 MacBook Air. Setting up docker-cli is easy, and I got docker-machine via brew, no problem. 
The issue seems to be VirtualBox. The Apple Silicon version is still in beta. 
I tried installing it via brew (`brew install --cask homebrew/cask-versions/virtualbox-beta`) or via the pkg from the website, but in both cases I run into the following issue while doing `make build`:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp

make: *** [vagrant-up] Error 1
```

After some google research it looks like some issue with macOs permissions for Kernel extensions? not sure though.

**Comment by stenh0use** [comment]
Hey @ceinem that looks like a virtualbox error. I don't have an arm laptop to test from, and given that virtualbox isnt supported yet I'm not sure I can give you a working solution.

As the error comes form the network side you could try changing the network config in the vagrant file. Otherwise best bet would be to head over to the virtualbox repo and try posting an issue there.

I'm sorry I can't really help you any further on that.

**Comment by ceinem** [comment]
Hey @stenh0use thanks for the quick response. Yes, absolutely, seems to be some issue with VirtualBox. it's a beta version, so anyways a long shot trying to get it all running. 
I'll head over there and ask around. If I manage to get everything working I'll post it here, in case other people want to try it. 
Thanks!

**Comment by stenh0use** [comment]
@ceinem I haven't been doing much with this project of late, but I've recently been working on it again. If you haven't found a solution yet, I'd recommend [colima](https://github.com/abiosoft/colima) as a really solid option for docker on mac. It also looks like VirtualBox gave up on the Arm functionality as it never graduated out of Beta and it hasn't been updated since 17-Apr-2023.
