### ISSUE TITLE
Deprecation of docker machine?

### ISSUE THREAD

**Issue by jucor** [spookiej/docker-machine-for-mac#7]
Hi! 
Thanks for sharing a way out of Docker for Desktop and its resource-intensive approach.
 `README.md` instructs to install Docker Machine with [ this link](https://docs.docker.com/machine/). Sadly that linked page says that docker-machine is now deprecated  and that ... Docker Desktop replaces it  :( Was it already the case when you kindly set up that repo, or is it a new development that will hamper its viability?
Thanks for clarifying for a historically linux Docker user new to Docker on macOS   :)

**Comment by stenh0use** [comment]
Hey jucor,

docker-machine was deprecated when I set the repo up. The way I am using docker-machine doesn't play much of a part in setting up docker. It basically ensures all your certificates and TCP endpoints are set up properly. It then gives a cli client to manage that integration. I never really run the docker machine cli.

If the deprecated part worries you, someone in the HN comments mentioned that [gitlab maintains a fork](https://gitlab.com/gitlab-org/ci-cd/docker-machine) since docker depreciated it. I'll look at updating that to the gitlab link.

Thanks!

**Comment by stenh0use** [comment]
Ok, I've just updated the README with the gitlab install instructions: https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/main/docs/install-machine.md

**Comment by jucor** [comment]
Awesome. Thank you!
